"""AUTO-GENERATED by generate_frozen_reference.py --overwrite (2026-09-21T02:21:11Z).

Frozen, fully expanded cobaya configuration for example2
(source: EXAMPLE_EVALUATE2.yaml resolved against the likelihood defaults of that day).
Do not edit by hand: the SHA-256 manifest pins this file, and any edit
makes every test fail. Regenerate deliberately instead.
"""

# The exact sampled-parameter point the reference chi2 was evaluated at
point = {
    "As_1e9": 2.1,
    "DES_A1_1": -0.7,
    "DES_A1_2": -1.7,
    "DES_A2_1": 0.0,
    "DES_A2_2": -1.51541,
    "DES_B1_1": 1.5,
    "DES_B1_2": 1.8,
    "DES_B1_3": 1.8,
    "DES_B1_4": 1.9,
    "DES_B1_5": 2.3,
    "DES_B1_6": 2.3,
    "DES_BARYON_Q1": 0.0,
    "DES_BARYON_Q2": 0.0,
    "DES_BTA_1": 0.0,
    "DES_DZ2_L1": 0.98,
    "DES_DZ2_L2": 1.31,
    "DES_DZ2_L3": 0.87,
    "DES_DZ2_L4": 0.92,
    "DES_DZ2_L5": 1.08,
    "DES_DZ2_L6": 0.845,
    "DES_DZ_L1": -0.009,
    "DES_DZ_L2": -0.035,
    "DES_DZ_L3": -0.005,
    "DES_DZ_L4": -0.007,
    "DES_DZ_L5": 0.002,
    "DES_DZ_L6": 0.002,
    "DES_DZ_S1": 0.0,
    "DES_DZ_S2": 0.0,
    "DES_DZ_S3": 0.0,
    "DES_DZ_S4": 0.0,
    "DES_M1": -0.0063,
    "DES_M2": -0.0198,
    "DES_M3": -0.0241,
    "DES_M4": -0.0369,
    "DES_PM1": 0.0,
    "DES_PM2": 0.0,
    "DES_PM3": 0.0,
    "DES_PM4": 0.0,
    "DES_PM5": 0.0,
    "DES_PM6": 0.0,
    "H0": 67.32,
    "mnu": 0.06,
    "ns": 0.96605,
    "omegab": 0.04,
    "omegam": 0.3,
    "w": -1.0,
    "w0pwa": -1.0
}

# Every option and every parameter written out explicitly: changing the
# live EXAMPLE_EVALUATE yaml files or the likelihood default yaml files
# does not affect this configuration
yaml_string = r"""
params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.2
    proposal: 0.2
    latex: 10^9 A_\mathrm{s}
    drop: true
    renames: A
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.015
    proposal: 0.015
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.32
      scale: 3
    proposal: 3
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.0495
      scale: 0.005
    proposal: 0.005
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.1
      max: 0.9
    ref:
      dist: norm
      loc: 0.316
      scale: 0.015
    proposal: 0.015
    latex: \Omega_\mathrm{m}
    drop: true
  w:
    prior:
      min: -3
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}
  w0pwa:
    prior:
      min: -5
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.05
    proposal: 0.05
    latex: w_{0,\mathrm{DE}}+w_{a,\mathrm{DE}}
    drop: true
  wa:
    value: 'lambda w0pwa, w: w0pwa - w'
    latex: w_{a,\mathrm{DE}}
    derived: true
  mnu:
    prior:
      min: 0.06
      max: 0.6
    ref:
      dist: norm
      loc: 0.25
      scale: 0.1
    proposal: 0.05
  tau:
    value: 0.0697186
    latex: \tau_\mathrm{reio}
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
    derived: true
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
    derived: true
    renames:
    - ombh2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
    derived: true
    renames:
    - omch2
  omegal:
    latex: \Omega_\Lambda
    derived: true
    renames:
    - omega_de
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  sigma8:
    latex: \sigma_8
    derived: true
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  s8:
    derived: 'lambda sigma8, omegam: sigma8*(omegam/0.3)**0.5'
    latex: S_8
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
    derived: true
  rdrag:
    latex: r_\mathrm{drag}
    derived: true
  yheused:
    latex: Y_P^\mathrm{BBN}
    derived: true
    renames:
    - YHe
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
    derived: true
    renames:
    - omnuh2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  DES_BARYON_Q1:
    latex: Q_\mathrm{DES}^1
    prior:
      min: 0.0
      max: 7.0
    ref:
      dist: norm
      loc: 2.0
      scale: 0.5
    proposal: 0.5
  DES_BARYON_Q2:
    latex: Q_\mathrm{DES}^2
    prior:
      min: -4.0
      max: 4.0
    ref:
      dist: norm
      loc: 2.0
      scale: 0.5
    proposal: 0.5
  DES_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.018
    ref:
      dist: norm
      loc: 0.0
      scale: 0.018
    proposal: 0.009
    latex: \Delta z_\mathrm{s,DES}^1
  DES_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.015
    ref:
      dist: norm
      loc: 0.0
      scale: 0.015
    proposal: 0.0075
    latex: \Delta z_\mathrm{s,DES}^2
  DES_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.011
    ref:
      dist: norm
      loc: 0.0
      scale: 0.011
    proposal: 0.0055
    latex: \Delta z_\mathrm{s,DES}^3
  DES_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.017
    ref:
      dist: norm
      loc: 0.0
      scale: 0.017
    proposal: 0.0085
    latex: \Delta z_\mathrm{s,DES}^4
  DES_A1_1:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: 0.7
      scale: 0.5
    proposal: 0.75
    latex: A_\mathrm{1-IA,DES}^1
  DES_A1_2:
    prior:
      min: -5
      max: 5
    ref:
      dist: norm
      loc: -1.7
      scale: 0.5
    proposal: 0.75
    latex: A_\mathrm{1-IA,DES}^2
  DES_A1_3:
    value: 0
    latex: A_\mathrm{1-IA,DES}^3
  DES_A1_4:
    value: 0
    latex: A_\mathrm{1-IA,DES}^4
  DES_A2_1:
    prior:
      min: -5.0
      max: 5.0
    ref:
      dist: norm
      loc: -1.36
      scale: 0.2
    proposal: 0.2
    latex: A_\mathrm{2-IA,DES}^1
  DES_A2_2:
    prior:
      min: -5.0
      max: 5.0
    ref:
      dist: norm
      loc: -2.5
      scale: 0.2
    proposal: 0.2
    latex: A_\mathrm{2-IA,DES}^2
  DES_A2_3:
    value: 0.0
    latex: A_\mathrm{2-IA,DES}^3
  DES_A2_4:
    value: 0.0
    latex: A_\mathrm{2-IA,DES}^4
  DES_BTA_1:
    prior:
      min: 0.0
      max: 2.0
    ref:
      dist: norm
      loc: 1.0
      scale: 0.1
    proposal: 0.1
    latex: A_\mathrm{BTA-IA,DES}^1
  DES_BTA_2:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^2
  DES_BTA_3:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^3
  DES_BTA_4:
    value: 0
    latex: A_\mathrm{BTA-IA,DES}^4
  DES_M1:
    prior:
      dist: norm
      loc: -0.0063
      scale: 0.0091
    ref:
      dist: norm
      loc: -0.0063
      scale: 0.0091
    proposal: 0.0045
    latex: m_\mathrm{DES}^1
  DES_M2:
    prior:
      dist: norm
      loc: -0.0198
      scale: 0.0078
    ref:
      dist: norm
      loc: -0.0198
      scale: 0.0078
    proposal: 0.004
    latex: m_\mathrm{DES}^2
  DES_M3:
    prior:
      dist: norm
      loc: -0.0241
      scale: 0.0076
    ref:
      dist: norm
      loc: -0.0241
      scale: 0.0076
    proposal: 0.004
    latex: m_\mathrm{DES}^3
  DES_M4:
    prior:
      dist: norm
      loc: -0.0369
      scale: 0.0076
    ref:
      dist: norm
      loc: -0.0369
      scale: 0.0076
    proposal: 0.004
    latex: m_\mathrm{DES}^4
  DES_BARYON_Q3:
    value: 0.0
    latex: Q_\mathrm{DES}^3
  DES_BARYON_Q4:
    value: 0.0
    latex: Q_\mathrm{DES}^4
  DES_DZ_L1:
    prior:
      dist: norm
      loc: -0.009
      scale: 0.007
    ref:
      dist: norm
      loc: -0.009
      scale: 0.007
    proposal: 0.0035
    latex: \Delta z_\mathrm{l,DES}^1
  DES_DZ_L2:
    prior:
      dist: norm
      loc: -0.035
      scale: 0.011
    ref:
      dist: norm
      loc: -0.035
      scale: 0.011
    proposal: 0.0055
    latex: \Delta z_\mathrm{l,DES}^2
  DES_DZ_L3:
    prior:
      dist: norm
      loc: -0.005
      scale: 0.006
    ref:
      dist: norm
      loc: -0.005
      scale: 0.006
    proposal: 0.003
    latex: \Delta z_\mathrm{l,DES}^3
  DES_DZ_L4:
    prior:
      dist: norm
      loc: -0.007
      scale: 0.006
    ref:
      dist: norm
      loc: -0.007
      scale: 0.006
    proposal: 0.003
    latex: \Delta z_\mathrm{l,DES}^4
  DES_DZ_L5:
    prior:
      dist: norm
      loc: 0.002
      scale: 0.007
    ref:
      dist: norm
      loc: 0.002
      scale: 0.007
    proposal: 0.0035
    latex: \Delta z_\mathrm{l,DES}^5
  DES_DZ_L6:
    prior:
      dist: norm
      loc: 0.002
      scale: 0.008
    ref:
      dist: norm
      loc: 0.002
      scale: 0.008
    proposal: 0.004
    latex: \Delta z_\mathrm{l,DES}^6
  DES_B1_1:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.5
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-DES}^1
  DES_B1_2:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.6
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-DES}^2
  DES_B1_3:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.7
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-DES}^3
  DES_B1_4:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 1.8
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-DES}^4
  DES_B1_5:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 2.0
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-DES}^5
  DES_B1_6:
    prior:
      min: 0.8
      max: 3
    ref:
      dist: norm
      loc: 2.2
      scale: 0.1
    proposal: 0.1
    latex: b_\mathrm{1-DES}^6
  DES_B2_1:
    value: 0.0
    latex: b_\mathrm{2-DES}^1
  DES_B2_2:
    value: 0.0
    latex: b_\mathrm{2-DES}^2
  DES_B2_3:
    value: 0.0
    latex: b_\mathrm{2-DES}^3
  DES_B2_4:
    value: 0.0
    latex: b_\mathrm{2-DES}^4
  DES_B2_5:
    value: 0.0
    latex: b_\mathrm{2-DES}^5
  DES_B2_6:
    value: 0.0
    latex: b_\mathrm{2-DES}^6
  DES_BMAG_1:
    value: 0.43
    latex: b_\mathrm{BMAG-DES}^1
  DES_BMAG_2:
    value: 0.3
    latex: b_\mathrm{BMAG-DES}^2
  DES_BMAG_3:
    value: 1.75
    latex: b_\mathrm{BMAG-DES}^3
  DES_BMAG_4:
    value: 1.94
    latex: b_\mathrm{BMAG-DES}^4
  DES_BMAG_5:
    value: 1.56
    latex: b_\mathrm{BMAG-DES}^5
  DES_BMAG_6:
    value: 2.96
    latex: b_\mathrm{BMAG-DES}^6
  DES_DZ2_L1:
    prior:
      dist: norm
      loc: 0.975
      scale: 0.062
    ref:
      dist: norm
      loc: 0.975
      scale: 0.062
    proposal: 0.03
    latex: \sigma z_\mathrm{l,DES}^1
  DES_DZ2_L2:
    prior:
      dist: norm
      loc: 1.306
      scale: 0.093
    ref:
      dist: norm
      loc: 1.306
      scale: 0.093
    proposal: 0.045
    latex: \sigma z_\mathrm{l,DES}^2
  DES_DZ2_L3:
    prior:
      dist: norm
      loc: 0.87
      scale: 0.054
    ref:
      dist: norm
      loc: 0.87
      scale: 0.054
    proposal: 0.025
    latex: \sigma z_\mathrm{l,DES}^3
  DES_DZ2_L4:
    prior:
      dist: norm
      loc: 0.918
      scale: 0.051
    ref:
      dist: norm
      loc: 0.918
      scale: 0.051
    proposal: 0.025
    latex: \sigma z_\mathrm{l,DES}^4
  DES_DZ2_L5:
    prior:
      dist: norm
      loc: 1.08
      scale: 0.067
    ref:
      dist: norm
      loc: 1.08
      scale: 0.067
    proposal: 0.0335
    latex: \sigma z_\mathrm{l,DES}^5
  DES_DZ2_L6:
    prior:
      dist: norm
      loc: 0.845
      scale: 0.073
    ref:
      dist: norm
      loc: 0.845
      scale: 0.073
    proposal: 0.0365
    latex: \sigma z_\mathrm{l,DES}^6
  DES_PM1:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^1
  DES_PM2:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^2
  DES_PM3:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^3
  DES_PM4:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^4
  DES_PM5:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^5
  DES_PM6:
    prior:
      dist: norm
      loc: 0.0
      scale: 25
    ref:
      dist: norm
      loc: 0.0
      scale: 25
    proposal: 5
    latex: PM_\mathrm{DES}^6
likelihood:
  desy1xplanck.combo_6x2pt:
    path: ./projects/desy1xplanck/tests/frozen/data
    data_file: Y3xPlanckPR4.dataset
    accuracyboost: 1.0
    integration_accuracy: 0
    lmax: 75000
    kmax_boltzmann: 7.5
    speed: 1
    non_linear_emul: 2
    external_nz_modeling: 0
    use_emulator: 0
    debug: false
    IA_redshift_evolution: 3
    IA_model: 0
    IA_code: 0
    bias_model:
    - 0
    - 0
    - 0
    - 1
    - 0
    add_baryons_on_dv: false
    which_bsims_add_on_dv: antilles-2
    use_baryon_pca: false
    create_baryon_pca: false
    baryon_pca_select_sims: antilles-2-99/antilles-101-378/antilles-380-400
    filename_baryon_pca: ./projects/lsst_y1/chains/pca.txt
    external_baryon_suppression: false
    print_datavector: false
    print_datavector_file: ./projects/desy1xplanck/chains/theory.modelvector
    type: []
    stop_at_error: false
    version: null
    input_params:
    - H0
    - As
    - DES_BARYON_Q1
    - DES_BARYON_Q2
    - DES_DZ_S1
    - DES_DZ_S2
    - DES_DZ_S3
    - DES_DZ_S4
    - DES_A1_1
    - DES_A1_2
    - DES_A1_3
    - DES_A1_4
    - DES_A2_1
    - DES_A2_2
    - DES_A2_3
    - DES_A2_4
    - DES_BTA_1
    - DES_BTA_2
    - DES_BTA_3
    - DES_BTA_4
    - DES_M1
    - DES_M2
    - DES_M3
    - DES_M4
    - DES_BARYON_Q3
    - DES_BARYON_Q4
    - DES_DZ_L1
    - DES_DZ_L2
    - DES_DZ_L3
    - DES_DZ_L4
    - DES_DZ_L5
    - DES_DZ_L6
    - DES_B1_1
    - DES_B1_2
    - DES_B1_3
    - DES_B1_4
    - DES_B1_5
    - DES_B1_6
    - DES_B2_1
    - DES_B2_2
    - DES_B2_3
    - DES_B2_4
    - DES_B2_5
    - DES_B2_6
    - DES_BMAG_1
    - DES_BMAG_2
    - DES_BMAG_3
    - DES_BMAG_4
    - DES_BMAG_5
    - DES_BMAG_6
    - DES_DZ2_L1
    - DES_DZ2_L2
    - DES_DZ2_L3
    - DES_DZ2_L4
    - DES_DZ2_L5
    - DES_DZ2_L6
    - DES_PM1
    - DES_PM2
    - DES_PM3
    - DES_PM4
    - DES_PM5
    - DES_PM6
    output_params: []
theory:
  camb:
    version: 1.6.7
    path: ./external_modules/code/CAMB
    speed: 0.3
    stop_at_error: false
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.0
      lens_potential_accuracy: 1.0
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 12
      kmax: 10
    ignore_obsolete: false
    use_renames: true
    external_primordial_pk: false
    use_non_linear_ratio: false
    renames:
      omegabh2: ombh2
      omegach2: omch2
      omegal: omega_de
      omegak: omk
      yhe: YHe
      yheused: YHe
      YpBBN: Y_p
      omegan2: omnuh2
    input_params:
    - ns
    - As
    - H0
    - w
    - wa
    - mnu
    - tau
    - omegabh2
    - omegach2
    output_params:
    - omegal
    - sigma8
    - age
    - rdrag
    - yheused
    - omegan2
timing: false
"""
