timing: True
debug: False
stop_at_error: False

likelihood:
  lsst_y1.lsst_cosmic_shear:
    path: ./external_modules/data/lsst_y1
    data_file: LSST_Y1_emu_cosmic_shear.dataset
    
params:
  As_1e9:
    prior:
      min: 0.5
      max: 5
    ref:
      dist: norm
      loc: 2.1
      scale: 0.1
    proposal: 0.1
    latex: 10^9 A_\mathrm{s}
    drop: true
    renames: A
  ns:
    prior:
      min: 0.87
      max: 1.07
    ref:
      dist: norm
      loc: 0.96605
      scale: 0.005
    proposal: 0.005
    latex: n_\mathrm{s}
  H0:
    prior:
      min: 55
      max: 91
    ref:
      dist: norm
      loc: 67.32
      scale: 2
    proposal: 1
    latex: H_0
  omegab:
    prior:
      min: 0.03
      max: 0.07
    ref:
      dist: norm
      loc: 0.0495
      scale: 0.0025
    proposal: 0.0025
    latex: \Omega_\mathrm{b}
    drop: true
  omegam:
    prior:
      min: 0.1
      max: 0.9
    ref:
      dist: norm
      loc: 0.316
      scale: 0.01
    proposal: 0.01
    latex: \Omega_\mathrm{m}
    drop: true
  w:
    prior:
      min: -3
      max: -0.01
    ref:
      dist: norm
      loc: -0.99
      scale: 0.02
    proposal: 0.02
    latex: w_{0,\mathrm{DE}}
  mnu:
    value: 0.06
  tau:
    value: 0.0697186
    latex: \tau_\mathrm{reio}
  # ---------------------------------------------------------------------------------------
  # ------------------------------------- DERIVED PARAMETERS ------------------------------
  # ---------------------------------------------------------------------------------------
  # WARNING: DO NOT REMOVE omegabh2/omegach2/omegamh2/wa/As/ FROM DERIVED PARAMETERS
  # WARNING: DO NOT REMOVE THE DROP FLAG FROM omegab/omegam/As_1e9/w0pwa
  # SEE: github.com/CosmoLike/cocoa#warning-warning-warning-weak-lensing-yaml-files-in-cobaya-
  # --------------------------------------------------------------------------------------- 
  As:
    value: 'lambda As_1e9: 1e-9 * As_1e9'
    latex: A_\mathrm{s}
  omegabh2:
    value: 'lambda omegab, H0: omegab*(H0/100)**2'
    latex: \Omega_\mathrm{b} h^2
  omegach2:
    value: 'lambda omegam, omegab, mnu, H0: (omegam-omegab)*(H0/100)**2-(mnu*(3.046/3)**0.75)/94.0708'
    latex: \Omega_\mathrm{c} h^2
  omegal:
    latex: \Omega_\Lambda
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  sigma8:
    latex: \sigma_8
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
  rdrag:
    latex: r_\mathrm{drag}
  yheused:
    latex: Y_P^\mathrm{BBN}
  omegan2:
    latex: \Omega_\mathrm{\\nu} h^2
  omegan:
    derived: 'lambda omegan2, H0: omegan2/((H0/100)**2)'
    latex: \Omega_\mathrm{\\nu}
  # WL photo-z errors
  LSST_DZ_S1:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^1
  LSST_DZ_S2:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^2
  LSST_DZ_S3:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^3
  LSST_DZ_S4:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^4
  LSST_DZ_S5:
    prior:
      dist: norm
      loc: 0.0
      scale: 0.002
    ref:
      dist: norm
      loc: 0.0
      scale: 0.002
    proposal: 0.002
    latex: \Delta z_\mathrm{s,LSST}^5
  # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------
  # Intrinsic alignment
  LSST_A1_1:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: 0.5
      scale: 0.1
    proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^1
  LSST_A1_2:
    prior:
      min: -5
      max:  5
    ref:
      dist: norm
      loc: 0.
      scale: 0.1
    proposal: 0.5
    latex: A_\mathrm{1-IA,LSST}^2
  # ------------------------------------------------------------------------
 # ------------------------------------------------------------------------
 # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------
  
  # Shear calibration parameters
  LSST_M1:
    value: 0.0
    latex: m_\mathrm{LSST}^1
  LSST_M2:
    value: 0.0
    latex: m_\mathrm{LSST}^2
  LSST_M3:
    value: 0.0
    latex: m_\mathrm{LSST}^3
  LSST_M4:
    value: 0.0
    latex: m_\mathrm{LSST}^4
  LSST_M5:
    value: 0.0
    latex: m_\mathrm{LSST}^5
  # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------
  # ------------------------------------------------------------------------
  # WL photo-z errors
  LSST_BARYON_Q1:
    value: 0.0
    latex: Q1_\mathrm{LSST}^1
  LSST_BARYON_Q2:
    value: 0.0
    latex: Q2_\mathrm{LSST}^2
  LSST_BARYON_Q3:
    value: 0.0
    latex: Q3_\mathrm{LSST}^3
  LSST_BARYON_Q4:
    value: 0.0
    latex: Q4_\mathrm{LSST}^4
    
  # ------------------------------------------------------------------------

theory:
  camb:
    path: ./external_modules/code/CAMB
    stop_at_error: False
    use_renames: True
    extra_args:
      halofit_version: takahashi
      AccuracyBoost: 1.15
      lens_potential_accuracy: 1.0
      num_massive_neutrinos: 1
      nnu: 3.046
      dark_energy_model: ppf
      accurate_massive_neutrino_transfers: false
      k_per_logint: 20

emulator:
  probe: cosmic_shear
  io:
      savedir: ./projects/lsst_y1/yaml_files/y1_cosmic_shear/emu_output
      save_train_data: true
      save_intermediate_model: true
  shear_calib:
      mask: ./projects/lsst_y1/data/y1_emu_cosmic_shear/shear_calib_mask.npy
      prior_std: 0.005,0.005,0.005,0.005,0.005
  baryons:
      n_pcas_baryon: 3
      prior_Q1: -1000.,1000.
      prior_Q2: -1000.,1000.
      prior_Q3: -1000.,1000.
  galaxy_bias:
      mask: ./projects/lsst_y1/data/y1_emu_cosmic_shear/shear_calib_mask.npy
      bias_fid: 1.20596735,1.343531,1.48417312,1.6602848,1.96735326
      bias_prior: 0.8, 3.0
  training:
      emu_type: nn
      nn_model: 0
      dv_fid: ./projects/lsst_y1/data/lsst_y1_theory.modelvector
      chi_sq_cut: 1e+5
      n_train_iter: 4
      n_lhs: 16000
      n_resample: 16000
      batch_size: 80
      n_epochs: 50
  sampling:
      scalecut_mask: ./projects/lsst_y1/data/LSST_Y1_M1_GGLOLAP0.05.mask
      n_mcmc: 30000
      n_emcee_walkers: 100
      n_burn_in: 20000
      n_thin: 10
      temper0: 0.02
      temper_increment: 0.05
